"""empty message

Revision ID: 2916be9c993c
Revises: 
Create Date: 2018-10-25 16:00:03.177532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2916be9c993c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dk_classify',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_discount_coupons',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('spendMoney', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_goods',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_goodscolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_group_add',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('0', '1', '2', '3'), nullable=True),
    sa.Column('ptetime', sa.DateTime(), nullable=True),
    sa.Column('group_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dk_group_add_status'), 'dk_group_add', ['status'], unique=False)
    op.create_table('dk_superuser',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('real_name', sa.String(length=32), nullable=True),
    sa.Column('id_card', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('dk_address',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('pro_city_county', sa.String(length=128), nullable=False),
    sa.Column('addr', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Enum('0', '1'), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dk_address_is_default'), 'dk_address', ['is_default'], unique=False)
    op.create_table('dk_coupons_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupons_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('0', '1', '-1'), nullable=True),
    sa.ForeignKeyConstraint(['coupons_id'], ['dk_discount_coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dk_coupons_user_status'), 'dk_coupons_user', ['status'], unique=False)
    op.create_table('dk_goods_collect',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('0', '1'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dk_goods_collect_status'), 'dk_goods_collect', ['status'], unique=False)
    op.create_table('dk_goodsmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('classify_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classify_id'], ['dk_classify.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_goodstype',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('classify_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classify_id'], ['dk_classify.id'], ),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('dk_group_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['dk_group_add.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_goodssku',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('goodsid', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price_unit', sa.Float(precision=2), nullable=False),
    sa.Column('group_price', sa.Float(precision=2), nullable=True),
    sa.Column('pnum', sa.Integer(), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('package_price', sa.Float(precision=2), nullable=True),
    sa.Column('is_package', sa.Enum('0', '1'), nullable=True),
    sa.Column('is_check', sa.Enum('0', '1'), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['dk_goodscolor.id'], ),
    sa.ForeignKeyConstraint(['goodsid'], ['dk_goods.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['dk_goodsmodel.id'], ),
    sa.ForeignKeyConstraint(['typeid'], ['dk_goodstype.type_id'], ),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index(op.f('ix_dk_goodssku_is_check'), 'dk_goodssku', ['is_check'], unique=False)
    op.create_index(op.f('ix_dk_goodssku_is_package'), 'dk_goodssku', ['is_package'], unique=False)
    op.create_table('dk_coupons_sku',
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('coupons_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupons_id'], ['dk_discount_coupons.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['dk_goodssku.sku_id'], ),
    sa.PrimaryKeyConstraint('sku_id', 'coupons_id')
    )
    op.create_table('dk_goods_banner',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['dk_goodssku.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_goods_image',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=258), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['dk_goodssku.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_order_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('addr_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('coupons_id', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('WAIT_PAYMENT', 'WAIT_SHARE', 'WAIT_Shipping', 'WAIT_Receiving', 'WAIT_COMMENT', 'COMPLETE', 'CANCELED'), nullable=True),
    sa.Column('type', sa.Enum('1', '2', '3'), nullable=True),
    sa.Column('parent', sa.Enum('0', '1'), nullable=True),
    sa.Column('is_comment', sa.Enum('0', '1'), nullable=True),
    sa.Column('trade_no', sa.String(length=128), nullable=True),
    sa.Column('nonce_str', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['addr_id'], ['dk_address.id'], ),
    sa.ForeignKeyConstraint(['coupons_id'], ['dk_discount_coupons.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['dk_group_add.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['dk_goodssku.sku_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dk_order_info_is_comment'), 'dk_order_info', ['is_comment'], unique=False)
    op.create_index(op.f('ix_dk_order_info_parent'), 'dk_order_info', ['parent'], unique=False)
    op.create_index(op.f('ix_dk_order_info_status'), 'dk_order_info', ['status'], unique=False)
    op.create_index(op.f('ix_dk_order_info_type'), 'dk_order_info', ['type'], unique=False)
    op.create_table('dk_promotion_banner',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['dk_goodssku.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_comment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('images', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['dk_order_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_order_fund',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('1', '2', '3'), nullable=True),
    sa.Column('fundtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['dk_order_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dk_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dk_order_fund_status'), 'dk_order_fund', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dk_order_fund_status'), table_name='dk_order_fund')
    op.drop_table('dk_order_fund')
    op.drop_table('dk_comment')
    op.drop_table('dk_promotion_banner')
    op.drop_index(op.f('ix_dk_order_info_type'), table_name='dk_order_info')
    op.drop_index(op.f('ix_dk_order_info_status'), table_name='dk_order_info')
    op.drop_index(op.f('ix_dk_order_info_parent'), table_name='dk_order_info')
    op.drop_index(op.f('ix_dk_order_info_is_comment'), table_name='dk_order_info')
    op.drop_table('dk_order_info')
    op.drop_table('dk_goods_image')
    op.drop_table('dk_goods_banner')
    op.drop_table('dk_coupons_sku')
    op.drop_index(op.f('ix_dk_goodssku_is_package'), table_name='dk_goodssku')
    op.drop_index(op.f('ix_dk_goodssku_is_check'), table_name='dk_goodssku')
    op.drop_table('dk_goodssku')
    op.drop_table('dk_group_user')
    op.drop_table('dk_goodstype')
    op.drop_table('dk_goodsmodel')
    op.drop_index(op.f('ix_dk_goods_collect_status'), table_name='dk_goods_collect')
    op.drop_table('dk_goods_collect')
    op.drop_index(op.f('ix_dk_coupons_user_status'), table_name='dk_coupons_user')
    op.drop_table('dk_coupons_user')
    op.drop_index(op.f('ix_dk_address_is_default'), table_name='dk_address')
    op.drop_table('dk_address')
    op.drop_table('dk_user')
    op.drop_table('dk_superuser')
    op.drop_index(op.f('ix_dk_group_add_status'), table_name='dk_group_add')
    op.drop_table('dk_group_add')
    op.drop_table('dk_goodscolor')
    op.drop_table('dk_goods')
    op.drop_table('dk_discount_coupons')
    op.drop_table('dk_classify')
    # ### end Alembic commands ###
