"""empty message

Revision ID: 539082e1e38a
Revises: e047f1cbcd1b
Create Date: 2018-10-25 16:42:16.377986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '539082e1e38a'
down_revision = 'e047f1cbcd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dk_classify_type',
    sa.Column('classify_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classify_id'], ['dk_classify.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['dk_goodstype.type_id'], ),
    sa.PrimaryKeyConstraint('classify_id', 'type_id')
    )
    op.drop_constraint('dk_goodstype_ibfk_1', 'dk_goodstype', type_='foreignkey')
    op.drop_column('dk_goodstype', 'classify_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dk_goodstype', sa.Column('classify_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('dk_goodstype_ibfk_1', 'dk_goodstype', 'dk_classify', ['classify_id'], ['id'])
    op.drop_table('dk_classify_type')
    # ### end Alembic commands ###
