"""empty message

Revision ID: c2ebca010555
Revises: 539082e1e38a
Create Date: 2018-10-26 13:45:45.547912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2ebca010555'
down_revision = '539082e1e38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dk_classify_model',
    sa.Column('classify_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classify_id'], ['dk_classify.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['dk_goodsmodel.id'], ),
    sa.PrimaryKeyConstraint('classify_id', 'model_id')
    )
    op.drop_constraint('dk_goodsmodel_ibfk_1', 'dk_goodsmodel', type_='foreignkey')
    op.drop_column('dk_goodsmodel', 'classify_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dk_goodsmodel', sa.Column('classify_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('dk_goodsmodel_ibfk_1', 'dk_goodsmodel', 'dk_classify', ['classify_id'], ['id'])
    op.drop_table('dk_classify_model')
    # ### end Alembic commands ###
